export const API_ROUTES = {
    BASE: '/',
    FACTS: {
        GET_ALL: 'fact/getAll',
        GET: 'fact/getById',
        GET_BY_STREETCODE_ID: 'fact/getByStreetcodeId',
        CREATE: 'fact/create',
        UPDATE: 'fact/update',
        DELETE: 'fact/delete',
    },
    PARTNERS: {
        GET_ALL: 'partners/getAll',
        GET_SPONSORS: 'partners/getSponsors',
        GET: 'partners/getById',
        CREATE: 'partners/create',
        UPDATE: 'partners/update',
        DELETE: 'partners/delete',
    },
    TAGS: {
        GET_ALL: 'tags/getAll',
        GET: 'tags/getById',
        GET_BY_TITLE: 'tags/getByTitle',
        GET_BY_STREETCODE_ID: 'tags/getByStreetcodeId',
        CREATE: 'tags/create',
        UPDATE: 'tags/update',
        DELETE: 'tags/delete',
    },
    TERMS: {
        GET_ALL: 'terms/getAll',
        GET: 'terms/getById',
        CREATE: 'terms/create',
        UPDATE: 'terms/update',
        DELETE: 'terms/delete',
    },
    TEXTS: {
        GET_ALL: 'text/getAll',
        CREATE: 'text/create',
        GET: 'text/getById',
        UPDATE: 'text/update',
        DELETE: 'text/delete',
    },
    TIMELINE: {
        GET_ALL: 'timeline/getAll',
        GET: 'timeline/getById',
        CREATE: 'timeline/create',
        UPDATE: 'timeline/update',
        DELETE: 'timeline/delete',
    },
    TOPONYMS: {
        GET_ALL: 'toponym/getAll',
        CREATE: 'toponym/create',
        GET: 'toponym/getById',
        GET_BY_NAME: 'toponym/getByName',
        UPDATE: 'toponym/update',
        DELETE: 'toponym/delete',
    },
    SOURCES: {
        GET_ALL: 'source/getAll',
        GET: 'source/getById',
        GET_BY_STREETCODE_ID: 'source/getByStreetcodeId',
        CREATE: 'source/create',
        UPDATE: 'source/update',
        DELETE: 'source/delete',
    },
    TRANSACTION_LINKS: {
        GET_ALL: 'transactLinks/getAll',
        GET: 'transactLinks/getById',
        CREATE: 'transactLinks/create',
        UPDATE: 'transactLinks/update',
        DELETE: 'transactLinks/delete',
    },
    AUDIOS: {
        GET_ALL: 'audios/getAll',
        GET: 'audios/getById',
        CREATE: 'audios/create',
        UPDATE: 'audios/update',
        DELETE: 'audios/delete',
    },
    VIDEOS: {
        GET_ALL: 'videos/getAll',
        GET: 'videos/getById',
        CREATE: 'videos/create',
        UPDATE: 'videos/update',
        DELETE: 'videos/delete',
    },
    IMAGES: {
        GET_ALL: 'images/getAll',
        GET: 'images/getById',
        CREATE: 'images/create',
        UPDATE: 'images/update',
        DELETE: 'images/delete',
    },
    ARTS: {
        GET_ALL: 'arts/getAll',
        GET: 'arts/getById',
        CREATE: 'arts/create',
        UPDATE: 'arts/update',
        DELETE: 'arts/delete',
    },
    RELATED_FIGURES: {
        GET_ALL: 'relatedFigure/getAll',
        GET: 'relatedFigure/getById',
        GET_BY_STREETCODE_ID: 'relatedFigure/getByStreetcodeId',
        CREATE: 'relatedFigure/create',
        UPDATE: 'relatedFigure/update',
        DELETE: 'relatedFigure/delete',
    },
    STREETCODES: {
        GET_ALL: 'streetcode/getAll',
        GET_EVENTS: 'streetcode/getEvents',
        GET_PERSONS: 'streetcode/getPersons',
        GET: 'streetcode/getById',
        GET_BY_NAME: 'streetcode/getByName',
        GET_BY_TAG_ID: 'streetcode/getByTagId',
        GET_BY_INDEX: 'streetcode/getByIndex',
        CREATE: 'streetcode/create',
        UPDATE: 'streetcode/update',
        DELETE: 'streetcode/delete',
    },
    SUBTITLES: {
        GET_ALL: 'subtitle/getAll',
        GET: 'subtitle/getById',
        GET_BY_STREETCODE_ID: 'subtitle/getByStreetcodeId',
        CREATE: 'subtitle/create',
        UPDATE: 'subtitle/update',
        DELETE: 'subtitle/delete',
    },
}