const API_ROUTES = {
    BASE: '/',
    FACTS: {
        GET_ALL: 'facts/getAll',
        GET: 'facts/getById',
        GET_BY_STREETCODE_ID: 'facts/getByStreetcodeId',
        CREATE: 'facts/create',
        UPDATE: 'facts/update',
        DELETE: 'facts/delete',
    },
    PARTNERS: {
        GET_ALL: 'partners/getAll',
        GET_SPONSORS: 'partners/getSponsors',
        GET: 'partners/getById',
        CREATE: 'partners/create',
        UPDATE: 'partners/update',
        DELETE: 'partners/delete',
    },
    TAGS: {
        GET_ALL: 'tags/getAll',
        GET: 'tags/getById',
        GET_BY_TITLE: 'tags/getByTitle',
        GET_BY_STREETCODE_ID: 'tags/getByStreetcodeId',
        CREATE: 'tags/create',
        UPDATE: 'tags/update',
        DELETE: 'tags/delete',
    },
    TERMS: {
        GET_ALL: 'terms/getAll',
        GET: 'terms/getById',
        CREATE: 'terms/create',
        UPDATE: 'terms/update',
        DELETE: 'terms/delete',
    },
    TEXTS: {
        GET_ALL: 'text/getAll',
        CREATE: 'text/create',
        GET: 'text/getById',
        UPDATE: 'text/update',
        DELETE: 'text/delete',
    },
    TIMELINE: {
        GET_ALL: 'timeline/getAll',
        GET: 'timeline/getById',
        CREATE: 'timeline/create',
        UPDATE: 'timeline/update',
        DELETE: 'timeline/delete',
    },
    TOPONYMS: {
        GET_ALL: 'toponym/getAll',
        CREATE: 'toponym/create',
        GET: 'toponym/getById',
        GET_BY_NAME: 'toponym/getByName',
        UPDATE: 'toponym/update',
        DELETE: 'toponym/delete',
    },
    TRANSACTION_LINKS: {
        GET_ALL: 'transactLinks/getAll',
        GET: 'transactLinks/getById',
        CREATE: 'transactLinks/create',
        UPDATE: 'transactLinks/update',
        DELETE: 'transactLinks/delete',
    },
    AUDIOS: {
        GET_ALL: 'audios/getAll',
        GET: 'audios/getById',
        CREATE: 'audios/create',
        UPDATE: 'audios/update',
        DELETE: 'audios/delete',
    },
    VIDEOS: {
        GET_ALL: 'videos/getAll',
        GET: 'videos/getById',
        CREATE: 'videos/create',
        UPDATE: 'videos/update',
        DELETE: 'videos/delete',
    },
    IMAGES: {
        GET_ALL: 'images/getAll',
        GET: 'images/getById',
        CREATE: 'images/create',
        UPDATE: 'images/update',
        DELETE: 'images/delete',
    },
    ARTS: {
        GET_ALL: 'arts/getAll',
        GET: 'arts/getById',
        CREATE: 'arts/create',
        UPDATE: 'arts/update',
        DELETE: 'arts/delete',
    },
    STREETCODES: {
        GET_ALL: 'streetcodes/getAll',
        GET_EVENTS: 'streetcodes/getEvents',
        GET_PERSONS: 'streetcodes/getPersons',
        GET: 'streetcodes/getById',
        GET_BY_NAME: 'streetcodes/getByName',
        GET_BY_TAG_ID: 'streetcodes/getByTagId',
        GET_BY_INDEX: 'streetcodes/getByIndex',
        CREATE: 'streetcodes/create',
        UPDATE: 'streetcodes/update',
        DELETE: 'streetcodes/delete',
    },
    SUBTITLES: {
        GET_ALL: 'subtitle/getAll',
        GET: 'subtitle/getById',
        GET_BY_STREETCODE_ID: 'subtitle/getByStreetcodeId',
        CREATE: 'subtitle/create',
        UPDATE: 'subtitle/update',
        DELETE: 'subtitle/delete',
    },
};

export default API_ROUTES;
