export const BUTTON_LABELS = {
    SAVE: 'Зберегти',
    ADD: 'Додати',
    CLOSE: 'Закрити',
    CANCEL: 'Скасувати',
    SUBMIT: 'Підтвердити',
    PUBLISH: 'Опублікувати',
    DRAFT: 'Зберегти як чернетку',
    ADD_TAG: 'Додати тег',
    ADD_CONTEXT: 'Додати контекст',
    ADD_NEWS: 'Додати новину',
    ADD_CATEGORY: 'Додати категорію',
    ADD_PARTNER: 'Додати партнера',
    ADD_SOCIAL_NETWORK: 'Додати соціальну мережу',
    ADD_TEAM_MEMBER: 'Додати члена команди',
    ADD_POSITION: 'Додати позицію',
    ADD_VACANCY: 'Додати вакансію',
    ADD_PDF: 'Додати в кабінет',
    SAVE_STREETCODE: 'Зберегти history-код',
    CREATE_STREETCODE: 'Додати History-код',
    SEARCH_STREETCODE: 'Пошук history-кодів',
    SEARCH_TOPONYM: 'Пошук топонімів',
    CHOOSE_TEMPLATE: 'Обрати шаблон',
};
export default BUTTON_LABELS;
