import { ArtSlideTemplateEnum } from '@models/enums/art-slide-template';
import StreetcodeArtSlide from '@models/media/streetcode-art-slide.model';

const ALL_SLIDES_TEMPLATES: StreetcodeArtSlide[] = [
    {
        index: 1,
        streetcodeId: -1,
        template: ArtSlideTemplateEnum.OneToFour,
        streetcodeArts: [
            {
                index: 1,
                art: {
                    id: 0,
                    imageId: 0,
                    image: {
                        id: 0,
                        base64: 'iVBORw0KGgoAAAANSUhEUgAAAfgAAADgCAYAAADv2nQ9AAAAAXNSR0IArs4c6QAACXpJREFUeF7t1QEJADAMA8HVv9hK2GAynquDXAqZ3b3HESBAgAABAimBMfCpPoUhQIAAAQJfwMB7BAIECBAgEBQw8MFSRSJAgAABAgbeDxAgQIAAgaCAgQ+WKhIBAgQIEDDwfoAAAQIECAQFDHywVJEIECBAgICB9wMECBAgQCAoYOCDpYpEgAABAgQMvB8gQIAAAQJBAQMfLFUkAgQIECBg4P0AAQIECBAIChj4YKkiESBAgAABA+8HCBAgQIBAUMDAB0sViQABAgQIGHg/QIAAAQIEggIGPliqSAQIECBAwMD7AQIECBAgEBQw8MFSRSJAgAABAgbeDxAgQIAAgaCAgQ+WKhIBAgQIEDDwfoAAAQIECAQFDHywVJEIECBAgICB9wMECBAgQCAoYOCDpYpEgAABAgQMvB8gQIAAAQJBAQMfLFUkAgQIECBg4P0AAQIECBAIChj4YKkiESBAgAABA+8HCBAgQIBAUMDAB0sViQABAgQIGHg/QIAAAQIEggIGPliqSAQIECBAwMD7AQIECBAgEBQw8MFSRSJAgAABAgbeDxAgQIAAgaCAgQ+WKhIBAgQIEDDwfoAAAQIECAQFDHywVJEIECBAgICB9wMECBAgQCAoYOCDpYpEgAABAgQMvB8gQIAAAQJBAQMfLFUkAgQIECBg4P0AAQIECBAIChj4YKkiESBAgAABA+8HCBAgQIBAUMDAB0sViQABAgQIGHg/QIAAAQIEggIGPliqSAQIECBAwMD7AQIECBAgEBQw8MFSRSJAgAABAgbeDxAgQIAAgaCAgQ+WKhIBAgQIEDDwfoAAAQIECAQFDHywVJEIECBAgICB9wMECBAgQCAoYOCDpYpEgAABAgQMvB8gQIAAAQJBAQMfLFUkAgQIECBg4P0AAQIECBAIChj4YKkiESBAgAABA+8HCBAgQIBAUMDAB0sViQABAgQIGHg/QIAAAQIEggIGPliqSAQIECBAwMD7AQIECBAgEBQw8MFSRSJAgAABAgbeDxAgQIAAgaCAgQ+WKhIBAgQIEDDwfoAAAQIECAQFDHywVJEIECBAgICB9wMECBAgQCAoYOCDpYpEgAABAgQMvB8gQIAAAQJBAQMfLFUkAgQIECBg4P0AAQIECBAIChj4YKkiESBAgAABA+8HCBAgQIBAUMDAB0sViQABAgQIGHg/QIAAAQIEggIGPliqSAQIECBAwMD7AQIECBAgEBQw8MFSRSJAgAABAgbeDxAgQIAAgaCAgQ+WKhIBAgQIEDDwfoAAAQIECAQFDHywVJEIECBAgICB9wMECBAgQCAoYOCDpYpEgAABAgQMvB8gQIAAAQJBAQMfLFUkAgQIECBg4P0AAQIECBAIChj4YKkiESBAgAABA+8HCBAgQIBAUMDAB0sViQABAgQIGHg/QIAAAQIEggIGPliqSAQIECBAwMD7AQIECBAgEBQw8MFSRSJAgAABAgbeDxAgQIAAgaCAgQ+WKhIBAgQIEDDwfoAAAQIECAQFDHywVJEIECBAgICB9wMECBAgQCAoYOCDpYpEgAABAgQMvB8gQIAAAQJBAQMfLFUkAgQIECBg4P0AAQIECBAIChj4YKkiESBAgAABA+8HCBAgQIBAUMDAB0sViQABAgQIGHg/QIAAAQIEggIGPliqSAQIECBAwMD7AQIECBAgEBQw8MFSRSJAgAABAgbeDxAgQIAAgaCAgQ+WKhIBAgQIEDDwfoAAAQIECAQFDHywVJEIECBAgICB9wMECBAgQCAoYOCDpYpEgAABAgQMvB8gQIAAAQJBAQMfLFUkAgQIECBg4P0AAQIECBAIChj4YKkiESBAgAABA+8HCBAgQIBAUMDAB0sViQABAgQIGHg/QIAAAQIEggIGPliqSAQIECBAwMD7AQIECBAgEBQw8MFSRSJAgAABAgbeDxAgQIAAgaCAgQ+WKhIBAgQIEDDwfoAAAQIECAQFDHywVJEIECBAgICB9wMECBAgQCAoYOCDpYpEgAABAgQMvB8gQIAAAQJBAQMfLFUkAgQIECBg4P0AAQIECBAIChj4YKkiESBAgAABA+8HCBAgQIBAUMDAB0sViQABAgQIGHg/QIAAAQIEggIGPliqSAQIECBAwMD7AQIECBAgEBQw8MFSRSJAgAABAgbeDxAgQIAAgaCAgQ+WKhIBAgQIEDDwfoAAAQIECAQFDHywVJEIECBAgICB9wMECBAgQCAoYOCDpYpEgAABAgQMvB8gQIAAAQJBAQMfLFUkAgQIECBg4P0AAQIECBAIChj4YKkiESBAgAABA+8HCBAgQIBAUMDAB0sViQABAgQIGHg/QIAAAQIEggIGPliqSAQIECBAwMD7AQIECBAgEBQw8MFSRSJAgAABAgbeDxAgQIAAgaCAgQ+WKhIBAgQIEDDwfoAAAQIECAQFDHywVJEIECBAgICB9wMECBAgQCAoYOCDpYpEgAABAgQMvB8gQIAAAQJBAQMfLFUkAgQIECBg4P0AAQIECBAIChj4YKkiESBAgAABA+8HCBAgQIBAUMDAB0sViQABAgQIGHg/QIAAAQIEggIGPliqSAQIECBAwMD7AQIECBAgEBQw8MFSRSJAgAABAgbeDxAgQIAAgaCAgQ+WKhIBAgQIEDDwfoAAAQIECAQFDHywVJEIECBAgICB9wMECBAgQCAoYOCDpYpEgAABAgQMvB8gQIAAAQJBAQMfLFUkAgQIECBg4P0AAQIECBAIChj4YKkiESBAgAABA+8HCBAgQIBAUMDAB0sViQABAgQIGHg/QIAAAQIEggIGPliqSAQIECBAwMD7AQIECBAgEBQw8MFSRSJAgAABAgbeDxAgQIAAgaCAgQ+WKhIBAgQIEDDwfoAAAQIECAQFDHywVJEIECBAgICB9wMECBAgQCAoYOCDpYpEgAABAgQMvB8gQIAAAQJBAQMfLFUkAgQIECBg4P0AAQIECBAIChj4YKkiESBAgAABA+8HCBAgQIBAUMDAB0sViQABAgQIGHg/QIAAAQIEggIGPliqSAQIECBAwMD7AQIECBAgEBQw8MFSRSJAgAABAgbeDxAgQIAAgaCAgQ+WKhIBAgQIEDDwfoAAAQIECAQFDHywVJEIECBAgICB9wMECBAgQCAoYOCDpYpEgAABAgQMvB8gQIAAAQJBAQMfLFUkAgQIECBg4P0AAQIECBAIChj4YKkiESBAgAABA+8HCBAgQIBAUMDAB0sViQABAgQIPHJ2U44jB52iAAAAAElFTkSuQmCC',
                        blobName: 'name',
                        mimeType: 'image/svg',
                    },
                },
            },
        ],
    },
];

export default ALL_SLIDES_TEMPLATES;
