import { ArtSlideTemplateEnum } from '@models/enums/art-slide-template';
import { ModelState } from '@models/enums/model-state';
import { StreetcodeArtSlideCreateUpdate } from '@models/media/streetcode-art-slide.model';

// eslint-disable-next-line max-len
const TEMPLATE_IMAGE_BASE64 = 'iVBORw0KGgoAAAANSUhEUgAAAfgAAADgCAYAAADv2nQ9AAAAAXNSR0IArs4c6QAACXpJREFUeF7t1QEJADAMA8HVv9hK2GAynquDXAqZ3b3HESBAgAABAimBMfCpPoUhQIAAAQJfwMB7BAIECBAgEBQw8MFSRSJAgAABAgbeDxAgQIAAgaCAgQ+WKhIBAgQIEDDwfoAAAQIECAQFDHywVJEIECBAgICB9wMECBAgQCAoYOCDpYpEgAABAgQMvB8gQIAAAQJBAQMfLFUkAgQIECBg4P0AAQIECBAIChj4YKkiESBAgAABA+8HCBAgQIBAUMDAB0sViQABAgQIGHg/QIAAAQIEggIGPliqSAQIECBAwMD7AQIECBAgEBQw8MFSRSJAgAABAgbeDxAgQIAAgaCAgQ+WKhIBAgQIEDDwfoAAAQIECAQFDHywVJEIECBAgICB9wMECBAgQCAoYOCDpYpEgAABAgQMvB8gQIAAAQJBAQMfLFUkAgQIECBg4P0AAQIECBAIChj4YKkiESBAgAABA+8HCBAgQIBAUMDAB0sViQABAgQIGHg/QIAAAQIEggIGPliqSAQIECBAwMD7AQIECBAgEBQw8MFSRSJAgAABAgbeDxAgQIAAgaCAgQ+WKhIBAgQIEDDwfoAAAQIECAQFDHywVJEIECBAgICB9wMECBAgQCAoYOCDpYpEgAABAgQMvB8gQIAAAQJBAQMfLFUkAgQIECBg4P0AAQIECBAIChj4YKkiESBAgAABA+8HCBAgQIBAUMDAB0sViQABAgQIGHg/QIAAAQIEggIGPliqSAQIECBAwMD7AQIECBAgEBQw8MFSRSJAgAABAgbeDxAgQIAAgaCAgQ+WKhIBAgQIEDDwfoAAAQIECAQFDHywVJEIECBAgICB9wMECBAgQCAoYOCDpYpEgAABAgQMvB8gQIAAAQJBAQMfLFUkAgQIECBg4P0AAQIECBAIChj4YKkiESBAgAABA+8HCBAgQIBAUMDAB0sViQABAgQIGHg/QIAAAQIEggIGPliqSAQIECBAwMD7AQIECBAgEBQw8MFSRSJAgAABAgbeDxAgQIAAgaCAgQ+WKhIBAgQIEDDwfoAAAQIECAQFDHywVJEIECBAgICB9wMECBAgQCAoYOCDpYpEgAABAgQMvB8gQIAAAQJBAQMfLFUkAgQIECBg4P0AAQIECBAIChj4YKkiESBAgAABA+8HCBAgQIBAUMDAB0sViQABAgQIGHg/QIAAAQIEggIGPliqSAQIECBAwMD7AQIECBAgEBQw8MFSRSJAgAABAgbeDxAgQIAAgaCAgQ+WKhIBAgQIEDDwfoAAAQIECAQFDHywVJEIECBAgICB9wMECBAgQCAoYOCDpYpEgAABAgQMvB8gQIAAAQJBAQMfLFUkAgQIECBg4P0AAQIECBAIChj4YKkiESBAgAABA+8HCBAgQIBAUMDAB0sViQABAgQIGHg/QIAAAQIEggIGPliqSAQIECBAwMD7AQIECBAgEBQw8MFSRSJAgAABAgbeDxAgQIAAgaCAgQ+WKhIBAgQIEDDwfoAAAQIECAQFDHywVJEIECBAgICB9wMECBAgQCAoYOCDpYpEgAABAgQMvB8gQIAAAQJBAQMfLFUkAgQIECBg4P0AAQIECBAIChj4YKkiESBAgAABA+8HCBAgQIBAUMDAB0sViQABAgQIGHg/QIAAAQIEggIGPliqSAQIECBAwMD7AQIECBAgEBQw8MFSRSJAgAABAgbeDxAgQIAAgaCAgQ+WKhIBAgQIEDDwfoAAAQIECAQFDHywVJEIECBAgICB9wMECBAgQCAoYOCDpYpEgAABAgQMvB8gQIAAAQJBAQMfLFUkAgQIECBg4P0AAQIECBAIChj4YKkiESBAgAABA+8HCBAgQIBAUMDAB0sViQABAgQIGHg/QIAAAQIEggIGPliqSAQIECBAwMD7AQIECBAgEBQw8MFSRSJAgAABAgbeDxAgQIAAgaCAgQ+WKhIBAgQIEDDwfoAAAQIECAQFDHywVJEIECBAgICB9wMECBAgQCAoYOCDpYpEgAABAgQMvB8gQIAAAQJBAQMfLFUkAgQIECBg4P0AAQIECBAIChj4YKkiESBAgAABA+8HCBAgQIBAUMDAB0sViQABAgQIGHg/QIAAAQIEggIGPliqSAQIECBAwMD7AQIECBAgEBQw8MFSRSJAgAABAgbeDxAgQIAAgaCAgQ+WKhIBAgQIEDDwfoAAAQIECAQFDHywVJEIECBAgICB9wMECBAgQCAoYOCDpYpEgAABAgQMvB8gQIAAAQJBAQMfLFUkAgQIECBg4P0AAQIECBAIChj4YKkiESBAgAABA+8HCBAgQIBAUMDAB0sViQABAgQIGHg/QIAAAQIEggIGPliqSAQIECBAwMD7AQIECBAgEBQw8MFSRSJAgAABAgbeDxAgQIAAgaCAgQ+WKhIBAgQIEDDwfoAAAQIECAQFDHywVJEIECBAgICB9wMECBAgQCAoYOCDpYpEgAABAgQMvB8gQIAAAQJBAQMfLFUkAgQIECBg4P0AAQIECBAIChj4YKkiESBAgAABA+8HCBAgQIBAUMDAB0sViQABAgQIGHg/QIAAAQIEggIGPliqSAQIECBAwMD7AQIECBAgEBQw8MFSRSJAgAABAgbeDxAgQIAAgaCAgQ+WKhIBAgQIEDDwfoAAAQIECAQFDHywVJEIECBAgICB9wMECBAgQCAoYOCDpYpEgAABAgQMvB8gQIAAAQJBAQMfLFUkAgQIECBg4P0AAQIECBAIChj4YKkiESBAgAABA+8HCBAgQIBAUMDAB0sViQABAgQIGHg/QIAAAQIEggIGPliqSAQIECBAwMD7AQIECBAgEBQw8MFSRSJAgAABAgbeDxAgQIAAgaCAgQ+WKhIBAgQIEDDwfoAAAQIECAQFDHywVJEIECBAgICB9wMECBAgQCAoYOCDpYpEgAABAgQMvB8gQIAAAQJBAQMfLFUkAgQIECBg4P0AAQIECBAIChj4YKkiESBAgAABA+8HCBAgQIBAUMDAB0sViQABAgQIGHg/QIAAAQIEggIGPliqSAQIECBAwMD7AQIECBAgEBQw8MFSRSJAgAABAgbeDxAgQIAAgaCAgQ+WKhIBAgQIEDDwfoAAAQIECAQFDHywVJEIECBAgICB9wMECBAgQCAoYOCDpYpEgAABAgQMvB8gQIAAAQJBAQMfLFUkAgQIECBg4P0AAQIECBAIChj4YKkiESBAgAABA+8HCBAgQIBAUMDAB0sViQABAgQIPHJ2U44jB52iAAAAAElFTkSuQmCC';

const ALL_SLIDES_TEMPLATES: StreetcodeArtSlideCreateUpdate[] = [
    {
        index: 1,
        streetcodeId: -1,
        template: ArtSlideTemplateEnum.OneToFour,
        streetcodeArts: [
            {
                index: 1,
                art: {
                    id: 0,
                    imageId: 0,
                    image: {
                        id: 0,
                        base64: TEMPLATE_IMAGE_BASE64,
                        blobName: 'name',
                        mimeType: 'image/svg',
                    },
                },
            },
        ],
        modelState: ModelState.Created,
        isPersisted: false,
    },
    {
        index: 2,
        streetcodeId: -1,
        template: ArtSlideTemplateEnum.OneToFourAndFiveToSix,
        streetcodeArts: [
            {
                index: 1,
                art: {
                    id: -1,
                    imageId: -1,
                    image: {
                        id: -1,
                        base64: TEMPLATE_IMAGE_BASE64,
                        blobName: 'name',
                        mimeType: 'image/svg',
                    },
                },
            },
            {
                index: 2,
                art: {
                    id: -1,
                    imageId: -1,
                    image: {
                        id: -1,
                        base64: TEMPLATE_IMAGE_BASE64,
                        blobName: 'name',
                        mimeType: 'image/svg',
                    },
                },
            },
        ],
        modelState: ModelState.Created,
        isPersisted: false,
    },
];

export default ALL_SLIDES_TEMPLATES;
export { TEMPLATE_IMAGE_BASE64 };
