export const API_ROUTES = {
    BASE: '/',
    FACTS: {
        GET_ALL: 'facts/getFacts',
        GET_BY_ID: 'facts/getFact',
        GET_BY_STREETCODE_ID: 'facts/getFactsByStreetcodeId',
        CREATE: 'facts/createFact',
        UPDATE: 'facts/updateFact',
        DELETE: 'facts/deleteFact',
    },
    PARTNERS: {
        GET_ALL: 'partners/getPartners',
        GET_SPONSORS: 'partners/getSponsors',
        GET: 'partners/getPartner',
        CREATE: 'partners/createPartner',
        UPDATE: 'partners/updatePartner',
        DELETE: 'partners/deletePartner',
    },
    TAGS: {
        GET_ALL: 'tags/getTags',
        GET_BY_ID: 'tags/getTag',
        GET_BY_TITLE: 'tags/getTagByTitle',
        GET_BY_STREETCODE_ID: 'tags/getTagByStreetcodeId',
        CREATE: 'tags/createTag',
        UPDATE: 'tags/updateTag',
        DELETE: 'tags/deleteTag',
    },
    TERMS: {
        GET_ALL: 'terms/getTerms',
        GET_BY_ID: 'terms/getTerm',
        CREATE: 'terms/createTerm',
        UPDATE: 'terms/updateTerm',
        DELETE: 'terms/deleteTerm',
    },
    TEXTS: {
        GET_ALL: 'text/getText',
        CREATE: 'text/createText',
        GET: 'text/getText',
        UPDATE: 'text/updateText',
        DELETE: 'text/deleteText',
    },
    TIMELINE: {
        GET_ALL: 'timeline/getTimeline',
        GET: 'timeline/getTimelineById',
        CREATE: 'timeline/createTimeline',
        UPDATE: 'timeline/updateTimeline',
        DELETE: 'timeline/deleteTimeline',
    },
    TOPONYMS: {
        GET_ALL: 'toponym/getToponym',
        CREATE: 'toponym/createToponym',
        GET: 'toponym/getToponym',
        GET_BY_NAME: 'toponym/getToponymByName',
        UPDATE: 'toponym/updateToponym',
        DELETE: 'toponym/deleteToponym',
    },
    TRANSACTION_LINKS: {
        GET_ALL: 'transactLinks/getTransactLinks',
        GET: 'transactLinks/getTransactLink',
        CREATE: 'transactLinks/CreateTransactLink',
        UPDATE: 'transactLinks/updateTransactLink',
        DELETE: 'transactLinks/deleteTransactLink',
    },
    AUDIOS: {
        GET_ALL: 'audios/getAudios',
        GET: 'audios/getAudio',
        CREATE: 'audios/createAudio',
        UPDATE: 'audios/updateAudio',
        DELETE: 'audios/deleteAudio',
    },
    VIDEOS: {
        GET_ALL: 'videos/getVideos',
        GET: 'videos/getVideo',
        CREATE: 'videos/createVideo',
        UPDATE: 'videos/updateVideo',
        DELETE: 'videos/deleteVideo',
    },
    IMAGES: {
        GET_ALL: 'images/getImages',
        GET: 'images/getImage',
        CREATE: 'images/createImage',
        UPDATE: 'images/updateImage',
        DELETE: 'images/deleteImage',
    },
    ARTS: {
        GET_ALL: 'arts/getArts',
        GET: 'arts/getArt',
        CREATE: 'arts/createArt',
        UPDATE: 'arts/updateArt',
        DELETE: 'arts/deleteArt',
    },
    STREETCODES: {
        GET_ALL: 'streetcodes/getStreetcodes',
        GET_EVENTS: 'streetcodes/getEvents',
        GET_PERSONS: 'streetcodes/getPersons',
        GET: 'streetcodes/getStreetcodeById',
        GET_BY_NAME: 'streetcodes/getStreetcodeByName',
        GET_BY_TAG_ID: 'streetcodes/getStreetcodeByTagId',
        GET_BY_INDEX: 'streetcodes/getStreetcodeByIndex',
        CREATE: 'streetcodes/createStreetcode',
        UPDATE: 'streetcodes/updateStreetcode',
        DELETE: 'streetcodes/deleteStreetcode',
    },
    SUBTITLES: {
        GET_ALL: 'subtitle/getSubtitles',
        GET: 'subtitle/getSubtitleById',
        GET_BY_STREETCODE_ID: 'subtitle/getSubtitlesByStreetcodeId',
        CREATE: 'subtitle/createSubtitle',
        UPDATE: 'subtitle/updateSubtitle',
        DELETE: 'subtitle/deleteSubtitle',
    },
}